# Auto-generated by tools/codegen.py. DO NOT EDIT.
from pydantic import Field

from kiwoom.models.base import KiwoomBaseModel


class Au10001Request(KiwoomBaseModel):
    """접근토큰 발급 (au10001) 요청 모델"""

    grant_type: str = Field(..., description="grant_type - client_credentials 입력")
    appkey: str = Field(..., description="앱키")
    secretkey: str = Field(..., description="시크릿키")


class Au10001Response(KiwoomBaseModel):
    """접근토큰 발급 (au10001) 응답 모델"""

    expires_dt: str = Field(..., description="만료일")
    token_type: str = Field(..., description="토큰타입")
    token: str = Field(..., description="접근토큰")


class Au10002Request(KiwoomBaseModel):
    """접근토큰폐기 (au10002) 요청 모델"""

    appkey: str = Field(..., description="앱키")
    secretkey: str = Field(..., description="시크릿키")
    token: str = Field(..., description="접근토큰")


class Au10002Response(KiwoomBaseModel):
    """접근토큰폐기 (au10002) 응답 모델"""

    pass
