# Auto-generated by tools/codegen.py. DO NOT EDIT.
from typing import Optional

from kiwoom.api.base import BaseAPI
from kiwoom.models.auth import (
    Au10001Request,
    Au10001Response,
    Au10002Request,
    Au10002Response,
)


class AuthAPI(BaseAPI):
    """
    키움 auth API 관련 엔드포인트를 제공하는 클래스입니다.
    """

    async def au10001(
        self, request: Au10001Request, headers: Optional[dict] = None
    ) -> Au10001Response:
        """
        접근토큰 발급 (au10001)

        URL: /oauth2/token (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/oauth2/token",
            api_id="au10001",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Au10001Response.model_validate(response_json)

    async def au10002(
        self, request: Au10002Request, headers: Optional[dict] = None
    ) -> Au10002Response:
        """
        접근토큰폐기 (au10002)

        URL: /oauth2/revoke (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/oauth2/revoke",
            api_id="au10002",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Au10002Response.model_validate(response_json)
