# Auto-generated by tools/codegen.py. DO NOT EDIT.
from typing import Optional

from kiwoom.api.base import BaseAPI
from kiwoom.models.overseas import (
    F4Request,
    F4Response,
    F5Request,
    F5Response,
    FERequest,
    FEResponse,
    FTRequest,
    FTResponse,
    Usa01980Request,
    Usa01980Response,
    Usa01990Request,
    Usa01990Response,
    Usa06010Request,
    Usa06010Response,
    Usa06011Request,
    Usa06011Response,
    Usa06012Request,
    Usa06012Response,
    Usa06013Request,
    Usa06013Response,
    Usa06014Request,
    Usa06014Response,
    Usa06015Request,
    Usa06015Response,
    Usa06016Request,
    Usa06016Response,
    Usa10098Request,
    Usa10098Response,
    Usa10099Request,
    Usa10099Response,
    Usa10100Request,
    Usa10100Response,
    Usa10101Request,
    Usa10101Response,
    Usa10102Request,
    Usa10102Response,
    Usa10104Request,
    Usa10104Response,
    Usa10105Request,
    Usa10105Response,
    Usa20100Request,
    Usa20100Response,
    Usa20101Request,
    Usa20101Response,
    Usa20150Request,
    Usa20150Response,
    Usa20151Request,
    Usa20151Response,
    Usa20200Request,
    Usa20200Response,
    Usa20201Request,
    Usa20201Response,
    Usa20280Request,
    Usa20280Response,
    Usa20281Request,
    Usa20281Response,
    Usa20290Request,
    Usa20290Response,
    Usa20291Request,
    Usa20291Response,
    Usa20510Request,
    Usa20510Response,
    Usa20511Request,
    Usa20511Response,
    Usa20512Request,
    Usa20512Response,
    Usa20520Request,
    Usa20520Response,
    Usa20521Request,
    Usa20521Response,
    Usa20530Request,
    Usa20530Response,
    Usa20531Request,
    Usa20531Response,
    Usa20540Request,
    Usa20540Response,
    Usa20541Request,
    Usa20541Response,
    Usa20550Request,
    Usa20550Response,
    Usa20551Request,
    Usa20551Response,
    Usa20570Request,
    Usa20570Response,
    Usa20571Request,
    Usa20571Response,
    Usa20590Request,
    Usa20590Response,
    Usa20880Request,
    Usa20880Response,
    Usa20881Request,
    Usa20881Response,
    Usa20910Request,
    Usa20910Response,
    Usa20911Request,
    Usa20911Response,
    Usa20920Request,
    Usa20920Response,
    Usa20921Request,
    Usa20921Response,
    Usa20922Request,
    Usa20922Response,
    Usa20930Request,
    Usa20930Response,
    Usa20931Request,
    Usa20931Response,
    Usa20932Request,
    Usa20932Response,
    Usa20940Request,
    Usa20940Response,
    Usa20941Request,
    Usa20941Response,
    Usa20960Request,
    Usa20960Response,
    Usa20961Request,
    Usa20961Response,
    Usa20970Request,
    Usa20970Response,
    Usa20971Request,
    Usa20971Response,
    Usa20972Request,
    Usa20972Response,
    Usa21670Request,
    Usa21670Response,
    Usa21680Request,
    Usa21680Response,
    Usa21690Request,
    Usa21690Response,
    Usa21730Request,
    Usa21730Response,
    Usa21731Request,
    Usa21731Response,
    Usa21732Request,
    Usa21732Response,
    Usa23000Request,
    Usa23000Response,
    Usa23100Request,
    Usa23100Response,
    Usa23400Request,
    Usa23400Response,
    Usa23401Request,
    Usa23401Response,
    Usa23402Request,
    Usa23402Response,
    Usa24100Request,
    Usa24100Response,
    Usa24101Request,
    Usa24101Response,
    Usa24110Request,
    Usa24110Response,
    Usa24111Request,
    Usa24111Response,
    Usa24120Request,
    Usa24120Response,
    Usa24121Request,
    Usa24121Response,
    Usa24140Request,
    Usa24140Response,
    Usa24141Request,
    Usa24141Response,
    Usa24150Request,
    Usa24150Response,
    Usa24151Request,
    Usa24151Response,
    Usa24160Request,
    Usa24160Response,
    Usa24161Request,
    Usa24161Response,
    Usa24162Request,
    Usa24162Response,
    Usa24200Request,
    Usa24200Response,
    Usa24201Request,
    Usa24201Response,
    Usa24210Request,
    Usa24210Response,
    Usa24211Request,
    Usa24211Response,
    Usa24220Request,
    Usa24220Response,
    Usa24221Request,
    Usa24221Response,
    Usa24290Request,
    Usa24290Response,
    Usa24291Request,
    Usa24291Response,
    Usa24300Request,
    Usa24300Response,
    Usa26410Request,
    Usa26410Response,
    Usa26411Request,
    Usa26411Response,
    Usa26412Request,
    Usa26412Response,
    Usa26413Request,
    Usa26413Response,
    Usa26414Request,
    Usa26414Response,
    Ust20000Request,
    Ust20000Response,
    Ust20001Request,
    Ust20001Response,
    Ust20002Request,
    Ust20002Response,
    Ust20003Request,
    Ust20003Response,
    Ust21050Request,
    Ust21050Response,
    Ust21070Request,
    Ust21070Response,
    Ust21100Request,
    Ust21100Response,
    Ust21110Request,
    Ust21110Response,
    Ust21111Request,
    Ust21111Response,
    Ust21120Request,
    Ust21120Response,
    Ust21121Request,
    Ust21121Response,
    Ust21131Request,
    Ust21131Response,
    Ust21132Request,
    Ust21132Response,
    Ust21150Request,
    Ust21150Response,
    Ust21160Request,
    Ust21160Response,
    Ust21170Request,
    Ust21170Response,
    Ust21180Request,
    Ust21180Response,
    Ust21510Request,
    Ust21510Response,
    Ust21530Request,
    Ust21530Response,
    Ust21610Request,
    Ust21610Response,
    Ust21620Request,
    Ust21620Response,
    Ust21630Request,
    Ust21630Response,
    Ust21640Request,
    Ust21640Response,
    Ust21650Request,
    Ust21650Response,
    Ust21660Request,
    Ust21660Response,
    Ust21661Request,
    Ust21661Response,
    Ust31300Request,
    Ust31300Response,
    Ust31301Request,
    Ust31301Response,
    Ust31302Request,
    Ust31302Response,
    Ust31490Request,
    Ust31490Response,
)


class OverseasAPI(BaseAPI):
    """
    키움 overseas API 관련 엔드포인트를 제공하는 클래스입니다.
    """

    async def usa01980(
        self, request: Usa01980Request, headers: Optional[dict] = None
    ) -> Usa01980Response:
        """
        미국주식 실시간 종목 조회 순위 (usa01980)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa01980",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa01980Response.model_validate(response_json)

    async def usa01990(
        self, request: Usa01990Request, headers: Optional[dict] = None
    ) -> Usa01990Response:
        """
        미국주식 관심종목 등록 상위 (usa01990)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa01990",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa01990Response.model_validate(response_json)

    async def usa06010(
        self, request: Usa06010Request, headers: Optional[dict] = None
    ) -> Usa06010Response:
        """
        미국주식 틱 차트 (usa06010)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06010",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06010Response.model_validate(response_json)

    async def usa06011(
        self, request: Usa06011Request, headers: Optional[dict] = None
    ) -> Usa06011Response:
        """
        미국주식 분 차트 (usa06011)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06011",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06011Response.model_validate(response_json)

    async def usa06012(
        self, request: Usa06012Request, headers: Optional[dict] = None
    ) -> Usa06012Response:
        """
        미국주식 일 차트 (usa06012)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06012",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06012Response.model_validate(response_json)

    async def usa06013(
        self, request: Usa06013Request, headers: Optional[dict] = None
    ) -> Usa06013Response:
        """
        미국주식 주 차트 (usa06013)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06013",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06013Response.model_validate(response_json)

    async def usa06014(
        self, request: Usa06014Request, headers: Optional[dict] = None
    ) -> Usa06014Response:
        """
        미국주식 월 차트 (usa06014)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06014",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06014Response.model_validate(response_json)

    async def usa06015(
        self, request: Usa06015Request, headers: Optional[dict] = None
    ) -> Usa06015Response:
        """
        미국주식 년 차트 (usa06015)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06015",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06015Response.model_validate(response_json)

    async def usa06016(
        self, request: Usa06016Request, headers: Optional[dict] = None
    ) -> Usa06016Response:
        """
        미국주식 분기 차트 (usa06016)

        URL: /api/us/chart (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/chart",
            api_id="usa06016",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa06016Response.model_validate(response_json)

    async def usa10098(
        self, request: Usa10098Request, headers: Optional[dict] = None
    ) -> Usa10098Response:
        """
        미국주식 거래소구분 조회 (usa10098)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10098",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10098Response.model_validate(response_json)

    async def usa10099(
        self, request: Usa10099Request, headers: Optional[dict] = None
    ) -> Usa10099Response:
        """
        미국주식 종목리스트 (usa10099)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10099",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10099Response.model_validate(response_json)

    async def usa10100(
        self, request: Usa10100Request, headers: Optional[dict] = None
    ) -> Usa10100Response:
        """
        미국주식 종목 조회 (usa10100)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10100",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10100Response.model_validate(response_json)

    async def usa10101(
        self, request: Usa10101Request, headers: Optional[dict] = None
    ) -> Usa10101Response:
        """
        미국주식 업종리스트 (usa10101)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10101",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10101Response.model_validate(response_json)

    async def usa10102(
        self, request: Usa10102Request, headers: Optional[dict] = None
    ) -> Usa10102Response:
        """
        미국지수 리스트 (usa10102)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10102",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10102Response.model_validate(response_json)

    async def usa10104(
        self, request: Usa10104Request, headers: Optional[dict] = None
    ) -> Usa10104Response:
        """
        미국 ETF,ETN 리스트  (usa10104)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10104",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10104Response.model_validate(response_json)

    async def usa10105(
        self, request: Usa10105Request, headers: Optional[dict] = None
    ) -> Usa10105Response:
        """
        미국 ETF 카테고리 리스트 (usa10105)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa10105",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa10105Response.model_validate(response_json)

    async def usa20100(
        self, request: Usa20100Request, headers: Optional[dict] = None
    ) -> Usa20100Response:
        """
        미국주식 현재가 종목정보 (usa20100)

        URL: /api/us/mrkcond (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/mrkcond",
            api_id="usa20100",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20100Response.model_validate(response_json)

    async def usa20101(
        self, request: Usa20101Request, headers: Optional[dict] = None
    ) -> Usa20101Response:
        """
        미국주식 현재가 10호가 (usa20101)

        URL: /api/us/mrkcond (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/mrkcond",
            api_id="usa20101",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20101Response.model_validate(response_json)

    async def usa20150(
        self, request: Usa20150Request, headers: Optional[dict] = None
    ) -> Usa20150Response:
        """
        미국주식 상세 체결내역 (usa20150)

        URL: /api/us/mrkcond (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/mrkcond",
            api_id="usa20150",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20150Response.model_validate(response_json)

    async def usa20151(
        self, request: Usa20151Request, headers: Optional[dict] = None
    ) -> Usa20151Response:
        """
        미국주식 일별 체결내역 (usa20151)

        URL: /api/us/mrkcond (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/mrkcond",
            api_id="usa20151",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20151Response.model_validate(response_json)

    async def usa20200(
        self, request: Usa20200Request, headers: Optional[dict] = None
    ) -> Usa20200Response:
        """
        미국주식 관심종목 그룹 리스트 조회 (usa20200)

        URL: /api/us/watchlist (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/watchlist",
            api_id="usa20200",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20200Response.model_validate(response_json)

    async def usa20201(
        self, request: Usa20201Request, headers: Optional[dict] = None
    ) -> Usa20201Response:
        """
        미국주식 관심종목 그룹 상세 조회 (usa20201)

        URL: /api/us/watchlist (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/watchlist",
            api_id="usa20201",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20201Response.model_validate(response_json)

    async def usa20280(
        self, request: Usa20280Request, headers: Optional[dict] = None
    ) -> Usa20280Response:
        """
        미국주식 조건검색 목록조회 (usa20280)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="usa20280",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20280Response.model_validate(response_json)

    async def usa20281(
        self, request: Usa20281Request, headers: Optional[dict] = None
    ) -> Usa20281Response:
        """
        미국주식 조건검색 요청 일반 (usa20281)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="usa20281",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20281Response.model_validate(response_json)

    async def usa20290(
        self, request: Usa20290Request, headers: Optional[dict] = None
    ) -> Usa20290Response:
        """
        미국주식 조건검색 요청 실시간 (usa20290)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="usa20290",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20290Response.model_validate(response_json)

    async def usa20291(
        self, request: Usa20291Request, headers: Optional[dict] = None
    ) -> Usa20291Response:
        """
        미국주식 조건검색 실시간 해제 (usa20291)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="usa20291",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20291Response.model_validate(response_json)

    async def usa20510(
        self, request: Usa20510Request, headers: Optional[dict] = None
    ) -> Usa20510Response:
        """
        미국주식 기간별 등락률상위(주식/업종) (usa20510)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20510",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20510Response.model_validate(response_json)

    async def usa20511(
        self, request: Usa20511Request, headers: Optional[dict] = None
    ) -> Usa20511Response:
        """
        미국주식 기간별 등락률상위(ETF) (usa20511)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20511",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20511Response.model_validate(response_json)

    async def usa20512(
        self, request: Usa20512Request, headers: Optional[dict] = None
    ) -> Usa20512Response:
        """
        미국주식 기간별 등락률상위(관심종목) (usa20512)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20512",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20512Response.model_validate(response_json)

    async def usa20520(
        self, request: Usa20520Request, headers: Optional[dict] = None
    ) -> Usa20520Response:
        """
        미국주식 거래량급등락(주식/업종) (usa20520)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20520",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20520Response.model_validate(response_json)

    async def usa20521(
        self, request: Usa20521Request, headers: Optional[dict] = None
    ) -> Usa20521Response:
        """
        미국주식 거래량급등락(ETF) (usa20521)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20521",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20521Response.model_validate(response_json)

    async def usa20530(
        self, request: Usa20530Request, headers: Optional[dict] = None
    ) -> Usa20530Response:
        """
        미국주식 당일 거래량 상위(주식/업종) (usa20530)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20530",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20530Response.model_validate(response_json)

    async def usa20531(
        self, request: Usa20531Request, headers: Optional[dict] = None
    ) -> Usa20531Response:
        """
        미국주식 당일 거래량 상위(ETF) (usa20531)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20531",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20531Response.model_validate(response_json)

    async def usa20540(
        self, request: Usa20540Request, headers: Optional[dict] = None
    ) -> Usa20540Response:
        """
        미국주식 당일 거래대금 상위(주식/업종) (usa20540)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20540",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20540Response.model_validate(response_json)

    async def usa20541(
        self, request: Usa20541Request, headers: Optional[dict] = None
    ) -> Usa20541Response:
        """
        미국주식 당일 거래대금 상위(ETF) (usa20541)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20541",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20541Response.model_validate(response_json)

    async def usa20550(
        self, request: Usa20550Request, headers: Optional[dict] = None
    ) -> Usa20550Response:
        """
        미국주식 시가총액상위(주식/업종) (usa20550)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20550",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20550Response.model_validate(response_json)

    async def usa20551(
        self, request: Usa20551Request, headers: Optional[dict] = None
    ) -> Usa20551Response:
        """
        미국주식 시가총액상위(ETF) (usa20551)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20551",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20551Response.model_validate(response_json)

    async def usa20570(
        self, request: Usa20570Request, headers: Optional[dict] = None
    ) -> Usa20570Response:
        """
        미국주식 가격대별주가(주식/업종) (usa20570)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20570",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20570Response.model_validate(response_json)

    async def usa20571(
        self, request: Usa20571Request, headers: Optional[dict] = None
    ) -> Usa20571Response:
        """
        미국주식 가격대별주가(ETF) (usa20571)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20571",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20571Response.model_validate(response_json)

    async def usa20590(
        self, request: Usa20590Request, headers: Optional[dict] = None
    ) -> Usa20590Response:
        """
        미국주식 일별주가 (usa20590)

        URL: /api/us/mrkcond (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/mrkcond",
            api_id="usa20590",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20590Response.model_validate(response_json)

    async def usa20880(
        self, request: Usa20880Request, headers: Optional[dict] = None
    ) -> Usa20880Response:
        """
        키움 거래 상위 종목(미국주식) (usa20880)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20880",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20880Response.model_validate(response_json)

    async def usa20881(
        self, request: Usa20881Request, headers: Optional[dict] = None
    ) -> Usa20881Response:
        """
        키움 거래 상위 종목(미국 ETF) (usa20881)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20881",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20881Response.model_validate(response_json)

    async def usa20910(
        self, request: Usa20910Request, headers: Optional[dict] = None
    ) -> Usa20910Response:
        """
        미국주식 전일대비 등락률상위(주식/업종) (usa20910)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20910",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20910Response.model_validate(response_json)

    async def usa20911(
        self, request: Usa20911Request, headers: Optional[dict] = None
    ) -> Usa20911Response:
        """
        미국주식 전일대비 등락률상위(ETF) (usa20911)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20911",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20911Response.model_validate(response_json)

    async def usa20920(
        self, request: Usa20920Request, headers: Optional[dict] = None
    ) -> Usa20920Response:
        """
        미국주식 시가대비 등락률상위(주식/업종) (usa20920)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20920",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20920Response.model_validate(response_json)

    async def usa20921(
        self, request: Usa20921Request, headers: Optional[dict] = None
    ) -> Usa20921Response:
        """
        미국주식 시가대비 등락률상위(ETF) (usa20921)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20921",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20921Response.model_validate(response_json)

    async def usa20922(
        self, request: Usa20922Request, headers: Optional[dict] = None
    ) -> Usa20922Response:
        """
        미국주식 시가대비 등락률상위(관심종목) (usa20922)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20922",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20922Response.model_validate(response_json)

    async def usa20930(
        self, request: Usa20930Request, headers: Optional[dict] = None
    ) -> Usa20930Response:
        """
        미국주식 가격급등락(주식/업종) (usa20930)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20930",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20930Response.model_validate(response_json)

    async def usa20931(
        self, request: Usa20931Request, headers: Optional[dict] = None
    ) -> Usa20931Response:
        """
        미국주식 가격급등락(ETF) (usa20931)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20931",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20931Response.model_validate(response_json)

    async def usa20932(
        self, request: Usa20932Request, headers: Optional[dict] = None
    ) -> Usa20932Response:
        """
        미국주식 가격급등락(관심종목) (usa20932)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20932",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20932Response.model_validate(response_json)

    async def usa20940(
        self, request: Usa20940Request, headers: Optional[dict] = None
    ) -> Usa20940Response:
        """
        미국주식 누적 등락률 상위(주식/업종) (usa20940)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20940",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20940Response.model_validate(response_json)

    async def usa20941(
        self, request: Usa20941Request, headers: Optional[dict] = None
    ) -> Usa20941Response:
        """
        미국주식 누적 등락률 상위(ETF) (usa20941)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20941",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20941Response.model_validate(response_json)

    async def usa20960(
        self, request: Usa20960Request, headers: Optional[dict] = None
    ) -> Usa20960Response:
        """
        미국주식 전일 거래상위(주식/업종) (usa20960)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20960",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20960Response.model_validate(response_json)

    async def usa20961(
        self, request: Usa20961Request, headers: Optional[dict] = None
    ) -> Usa20961Response:
        """
        미국주식 전일 거래상위(ETF) (usa20961)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa20961",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20961Response.model_validate(response_json)

    async def usa20970(
        self, request: Usa20970Request, headers: Optional[dict] = None
    ) -> Usa20970Response:
        """
        미국주식 고가/저가 접근(주식/업종) (usa20970)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20970",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20970Response.model_validate(response_json)

    async def usa20971(
        self, request: Usa20971Request, headers: Optional[dict] = None
    ) -> Usa20971Response:
        """
        미국주식 고가/저가 접근(ETF) (usa20971)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20971",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20971Response.model_validate(response_json)

    async def usa20972(
        self, request: Usa20972Request, headers: Optional[dict] = None
    ) -> Usa20972Response:
        """
        미국주식 고가/저가 접근(관심종목) (usa20972)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa20972",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa20972Response.model_validate(response_json)

    async def usa21670(
        self, request: Usa21670Request, headers: Optional[dict] = None
    ) -> Usa21670Response:
        """
        미국주식 일별계좌수익률현황 (usa21670)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21670",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21670Response.model_validate(response_json)

    async def usa21680(
        self, request: Usa21680Request, headers: Optional[dict] = None
    ) -> Usa21680Response:
        """
        미국주식 월별계좌수익률현황 (usa21680)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21680",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21680Response.model_validate(response_json)

    async def usa21690(
        self, request: Usa21690Request, headers: Optional[dict] = None
    ) -> Usa21690Response:
        """
        미국주식 연도별계좌수익률현황 (usa21690)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21690",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21690Response.model_validate(response_json)

    async def usa21730(
        self, request: Usa21730Request, headers: Optional[dict] = None
    ) -> Usa21730Response:
        """
        미국주식 일별종목수익률현황 (usa21730)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21730",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21730Response.model_validate(response_json)

    async def usa21731(
        self, request: Usa21731Request, headers: Optional[dict] = None
    ) -> Usa21731Response:
        """
        미국주식 월별종목수익률현황 (usa21731)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21731",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21731Response.model_validate(response_json)

    async def usa21732(
        self, request: Usa21732Request, headers: Optional[dict] = None
    ) -> Usa21732Response:
        """
        미국주식 연도별종목수익률현황 (usa21732)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="usa21732",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa21732Response.model_validate(response_json)

    async def usa23000(
        self, request: Usa23000Request, headers: Optional[dict] = None
    ) -> Usa23000Response:
        """
        미국주식 업종별 기간별 수익률 조회 (usa23000)

        URL: /api/us/sect (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/sect",
            api_id="usa23000",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa23000Response.model_validate(response_json)

    async def usa23100(
        self, request: Usa23100Request, headers: Optional[dict] = None
    ) -> Usa23100Response:
        """
        미국주식 업종별 등락률 상위/하위 조회 (usa23100)

        URL: /api/us/sect (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/sect",
            api_id="usa23100",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa23100Response.model_validate(response_json)

    async def usa23400(
        self, request: Usa23400Request, headers: Optional[dict] = None
    ) -> Usa23400Response:
        """
        미국주식 거래량갱신(주식/업종) (usa23400)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa23400",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa23400Response.model_validate(response_json)

    async def usa23401(
        self, request: Usa23401Request, headers: Optional[dict] = None
    ) -> Usa23401Response:
        """
        미국주식 거래량갱신(ETF) (usa23401)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa23401",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa23401Response.model_validate(response_json)

    async def usa23402(
        self, request: Usa23402Request, headers: Optional[dict] = None
    ) -> Usa23402Response:
        """
        미국주식 거래량갱신(관심종목) (usa23402)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa23402",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa23402Response.model_validate(response_json)

    async def usa24100(
        self, request: Usa24100Request, headers: Optional[dict] = None
    ) -> Usa24100Response:
        """
        미국주식 신고가/신저가(주식/업종) (usa24100)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24100",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24100Response.model_validate(response_json)

    async def usa24101(
        self, request: Usa24101Request, headers: Optional[dict] = None
    ) -> Usa24101Response:
        """
        미국주식 신고가/신저가(ETF) (usa24101)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24101",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24101Response.model_validate(response_json)

    async def usa24110(
        self, request: Usa24110Request, headers: Optional[dict] = None
    ) -> Usa24110Response:
        """
        미국주식 최고최저가대비 상승하락(주식/업종) (usa24110)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24110",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24110Response.model_validate(response_json)

    async def usa24111(
        self, request: Usa24111Request, headers: Optional[dict] = None
    ) -> Usa24111Response:
        """
        미국주식 최고최저가대비 상승하락(ETF) (usa24111)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24111",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24111Response.model_validate(response_json)

    async def usa24120(
        self, request: Usa24120Request, headers: Optional[dict] = None
    ) -> Usa24120Response:
        """
        미국주식 특정일자 상승/하락 (주식/업종) (usa24120)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24120",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24120Response.model_validate(response_json)

    async def usa24121(
        self, request: Usa24121Request, headers: Optional[dict] = None
    ) -> Usa24121Response:
        """
        미국주식 특정일자 상승/하락(ETF) (usa24121)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24121",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24121Response.model_validate(response_json)

    async def usa24140(
        self, request: Usa24140Request, headers: Optional[dict] = None
    ) -> Usa24140Response:
        """
        미국주식 갭상승/갭하락(주식/업종) (usa24140)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24140",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24140Response.model_validate(response_json)

    async def usa24141(
        self, request: Usa24141Request, headers: Optional[dict] = None
    ) -> Usa24141Response:
        """
        미국주식 갭상승/갭하락(ETF) (usa24141)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24141",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24141Response.model_validate(response_json)

    async def usa24150(
        self, request: Usa24150Request, headers: Optional[dict] = None
    ) -> Usa24150Response:
        """
        미국주식 회전율 상위(주식/업종) (usa24150)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24150",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24150Response.model_validate(response_json)

    async def usa24151(
        self, request: Usa24151Request, headers: Optional[dict] = None
    ) -> Usa24151Response:
        """
        미국주식 회전율 상위(ETF) (usa24151)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24151",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24151Response.model_validate(response_json)

    async def usa24160(
        self, request: Usa24160Request, headers: Optional[dict] = None
    ) -> Usa24160Response:
        """
        미국주식 연속상승/하락 순위(주식/업종) (usa24160)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24160",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24160Response.model_validate(response_json)

    async def usa24161(
        self, request: Usa24161Request, headers: Optional[dict] = None
    ) -> Usa24161Response:
        """
        미국주식 연속상승/하락 순위(ETF) (usa24161)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24161",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24161Response.model_validate(response_json)

    async def usa24162(
        self, request: Usa24162Request, headers: Optional[dict] = None
    ) -> Usa24162Response:
        """
        미국주식 연속상승/하락 순위(관심종목) (usa24162)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24162",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24162Response.model_validate(response_json)

    async def usa24200(
        self, request: Usa24200Request, headers: Optional[dict] = None
    ) -> Usa24200Response:
        """
        미국주식 호가잔량상위(주식/업종) (usa24200)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24200",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24200Response.model_validate(response_json)

    async def usa24201(
        self, request: Usa24201Request, headers: Optional[dict] = None
    ) -> Usa24201Response:
        """
        미국주식 호가잔량상위(ETF) (usa24201)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24201",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24201Response.model_validate(response_json)

    async def usa24210(
        self, request: Usa24210Request, headers: Optional[dict] = None
    ) -> Usa24210Response:
        """
        미국주식 잔량률급증(주식/업종) (usa24210)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24210",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24210Response.model_validate(response_json)

    async def usa24211(
        self, request: Usa24211Request, headers: Optional[dict] = None
    ) -> Usa24211Response:
        """
        미국주식 잔량률급증(ETF) (usa24211)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24211",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24211Response.model_validate(response_json)

    async def usa24220(
        self, request: Usa24220Request, headers: Optional[dict] = None
    ) -> Usa24220Response:
        """
        미국주식 매물대집중(주식/업종) (usa24220)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24220",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24220Response.model_validate(response_json)

    async def usa24221(
        self, request: Usa24221Request, headers: Optional[dict] = None
    ) -> Usa24221Response:
        """
        미국주식 매물대집중(ETF) (usa24221)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa24221",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24221Response.model_validate(response_json)

    async def usa24290(
        self, request: Usa24290Request, headers: Optional[dict] = None
    ) -> Usa24290Response:
        """
        미국주식 주간거래 괴리율 상위(주식/업종) (usa24290)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24290",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24290Response.model_validate(response_json)

    async def usa24291(
        self, request: Usa24291Request, headers: Optional[dict] = None
    ) -> Usa24291Response:
        """
        미국주식 주간거래 괴리율 상위(ETF) (usa24291)

        URL: /api/us/rkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/rkinfo",
            api_id="usa24291",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24291Response.model_validate(response_json)

    async def usa24300(
        self, request: Usa24300Request, headers: Optional[dict] = None
    ) -> Usa24300Response:
        """
        미국주식 리서치(미국주식/ETF) (usa24300)

        URL: /api/us/invtinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/invtinfo",
            api_id="usa24300",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa24300Response.model_validate(response_json)

    async def usa26410(
        self, request: Usa26410Request, headers: Optional[dict] = None
    ) -> Usa26410Response:
        """
        미국주식 연도별 등락률(종목) (usa26410)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa26410",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa26410Response.model_validate(response_json)

    async def usa26411(
        self, request: Usa26411Request, headers: Optional[dict] = None
    ) -> Usa26411Response:
        """
        미국주식 연도별 업종별 종목등락률 (usa26411)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa26411",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa26411Response.model_validate(response_json)

    async def usa26412(
        self, request: Usa26412Request, headers: Optional[dict] = None
    ) -> Usa26412Response:
        """
        미국주식 연도별 ETF 카테고리별 종목등락률 (usa26412)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa26412",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa26412Response.model_validate(response_json)

    async def usa26413(
        self, request: Usa26413Request, headers: Optional[dict] = None
    ) -> Usa26413Response:
        """
        미국주식 연도별 등락률(업종) (usa26413)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa26413",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa26413Response.model_validate(response_json)

    async def usa26414(
        self, request: Usa26414Request, headers: Optional[dict] = None
    ) -> Usa26414Response:
        """
        미국주식 연도별 등락률(ETF) (usa26414)

        URL: /api/us/stkinfo (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/stkinfo",
            api_id="usa26414",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Usa26414Response.model_validate(response_json)

    async def ust20000(
        self, request: Ust20000Request, headers: Optional[dict] = None
    ) -> Ust20000Response:
        """
        미국주식 매수 주문 (ust20000)

        URL: /api/us/ordr (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/ordr",
            api_id="ust20000",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust20000Response.model_validate(response_json)

    async def ust20001(
        self, request: Ust20001Request, headers: Optional[dict] = None
    ) -> Ust20001Response:
        """
        미국주식 매도 주문 (ust20001)

        URL: /api/us/ordr (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/ordr",
            api_id="ust20001",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust20001Response.model_validate(response_json)

    async def ust20002(
        self, request: Ust20002Request, headers: Optional[dict] = None
    ) -> Ust20002Response:
        """
        미국주식 정정 주문 (ust20002)

        URL: /api/us/ordr (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/ordr",
            api_id="ust20002",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust20002Response.model_validate(response_json)

    async def ust20003(
        self, request: Ust20003Request, headers: Optional[dict] = None
    ) -> Ust20003Response:
        """
        미국주식 취소 주문 (ust20003)

        URL: /api/us/ordr (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/ordr",
            api_id="ust20003",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust20003Response.model_validate(response_json)

    async def ust21050(
        self, request: Ust21050Request, headers: Optional[dict] = None
    ) -> Ust21050Response:
        """
        미국주식 원장 미체결 (ust21050)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21050",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21050Response.model_validate(response_json)

    async def ust21070(
        self, request: Ust21070Request, headers: Optional[dict] = None
    ) -> Ust21070Response:
        """
        미국주식 원장잔고확인 (ust21070)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21070",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21070Response.model_validate(response_json)

    async def ust21100(
        self, request: Ust21100Request, headers: Optional[dict] = None
    ) -> Ust21100Response:
        """
        미국주식 거래내역 (ust21100)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21100",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21100Response.model_validate(response_json)

    async def ust21110(
        self, request: Ust21110Request, headers: Optional[dict] = None
    ) -> Ust21110Response:
        """
        해외주식 예수금 (ust21110)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21110",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21110Response.model_validate(response_json)

    async def ust21111(
        self, request: Ust21111Request, headers: Optional[dict] = None
    ) -> Ust21111Response:
        """
        원화출금가능 금액 조회(원화대용 포함) (ust21111)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21111",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21111Response.model_validate(response_json)

    async def ust21120(
        self, request: Ust21120Request, headers: Optional[dict] = None
    ) -> Ust21120Response:
        """
        통화별 예수금 및 증권 평가금현황 (ust21120)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21120",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21120Response.model_validate(response_json)

    async def ust21121(
        self, request: Ust21121Request, headers: Optional[dict] = None
    ) -> Ust21121Response:
        """
        해외증권 원장 평가금액현황 (ust21121)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21121",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21121Response.model_validate(response_json)

    async def ust21131(
        self, request: Ust21131Request, headers: Optional[dict] = None
    ) -> Ust21131Response:
        """
        해외증권 특정일 평가금액 (ust21131)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21131",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21131Response.model_validate(response_json)

    async def ust21132(
        self, request: Ust21132Request, headers: Optional[dict] = None
    ) -> Ust21132Response:
        """
        특정일 통화별 예수금 및 증권 평가금 (ust21132)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21132",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21132Response.model_validate(response_json)

    async def ust21150(
        self, request: Ust21150Request, headers: Optional[dict] = None
    ) -> Ust21150Response:
        """
        미국주식 일별 주문체결내역 (ust21150)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21150",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21150Response.model_validate(response_json)

    async def ust21160(
        self, request: Ust21160Request, headers: Optional[dict] = None
    ) -> Ust21160Response:
        """
        미국주식 예수금 상세 (ust21160)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21160",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21160Response.model_validate(response_json)

    async def ust21170(
        self, request: Ust21170Request, headers: Optional[dict] = None
    ) -> Ust21170Response:
        """
        미국주식 당일 종목별 실현손익 (ust21170)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21170",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21170Response.model_validate(response_json)

    async def ust21180(
        self, request: Ust21180Request, headers: Optional[dict] = None
    ) -> Ust21180Response:
        """
        미국주식 기간별 주문내역 (ust21180)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21180",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21180Response.model_validate(response_json)

    async def ust21510(
        self, request: Ust21510Request, headers: Optional[dict] = None
    ) -> Ust21510Response:
        """
        미국주식 당일 주문체결 확인 (ust21510)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21510",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21510Response.model_validate(response_json)

    async def ust21530(
        self, request: Ust21530Request, headers: Optional[dict] = None
    ) -> Ust21530Response:
        """
        미국주식 실현손익 (ust21530)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21530",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21530Response.model_validate(response_json)

    async def ust21610(
        self, request: Ust21610Request, headers: Optional[dict] = None
    ) -> Ust21610Response:
        """
        미국주식 당일매매 (ust21610)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21610",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21610Response.model_validate(response_json)

    async def ust21620(
        self, request: Ust21620Request, headers: Optional[dict] = None
    ) -> Ust21620Response:
        """
        미국주식 당일매매정리 (ust21620)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21620",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21620Response.model_validate(response_json)

    async def ust21630(
        self, request: Ust21630Request, headers: Optional[dict] = None
    ) -> Ust21630Response:
        """
        미국주식 당일 실현손익 (ust21630)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21630",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21630Response.model_validate(response_json)

    async def ust21640(
        self, request: Ust21640Request, headers: Optional[dict] = None
    ) -> Ust21640Response:
        """
        미국주식 일별 종목별 실현손익 (ust21640)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21640",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21640Response.model_validate(response_json)

    async def ust21650(
        self, request: Ust21650Request, headers: Optional[dict] = None
    ) -> Ust21650Response:
        """
        미국주식 기간별 수익률 현황 (ust21650)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21650",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21650Response.model_validate(response_json)

    async def ust21660(
        self, request: Ust21660Request, headers: Optional[dict] = None
    ) -> Ust21660Response:
        """
        미국주식 일별 실현손익 (ust21660)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21660",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21660Response.model_validate(response_json)

    async def ust21661(
        self, request: Ust21661Request, headers: Optional[dict] = None
    ) -> Ust21661Response:
        """
        미국주식 월별 실현손익 (ust21661)

        URL: /api/us/acnt (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/acnt",
            api_id="ust21661",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust21661Response.model_validate(response_json)

    async def ust31300(
        self, request: Ust31300Request, headers: Optional[dict] = None
    ) -> Ust31300Response:
        """
        환전 예상 금액 조회 (ust31300)

        URL: /api/us/exchange (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/exchange",
            api_id="ust31300",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust31300Response.model_validate(response_json)

    async def ust31301(
        self, request: Ust31301Request, headers: Optional[dict] = None
    ) -> Ust31301Response:
        """
        환율 조회 (ust31301)

        URL: /api/us/exchange (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/exchange",
            api_id="ust31301",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust31301Response.model_validate(response_json)

    async def ust31302(
        self, request: Ust31302Request, headers: Optional[dict] = None
    ) -> Ust31302Response:
        """
        환전 신청 (ust31302)

        URL: /api/us/exchange (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/exchange",
            api_id="ust31302",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust31302Response.model_validate(response_json)

    async def ust31490(
        self, request: Ust31490Request, headers: Optional[dict] = None
    ) -> Ust31490Response:
        """
        미국주식 주문가능수량(종목/증거금률별) (ust31490)

        URL: /api/us/ordr (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/ordr",
            api_id="ust31490",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return Ust31490Response.model_validate(response_json)

    async def F4(self, request: F4Request, headers: Optional[dict] = None) -> F4Response:
        """
        미국주식 실시간 주문 확인 (F4)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="F4",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return F4Response.model_validate(response_json)

    async def F5(self, request: F5Request, headers: Optional[dict] = None) -> F5Response:
        """
        미국주식 실시간 체결 (F5)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="F5",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return F5Response.model_validate(response_json)

    async def FE(self, request: FERequest, headers: Optional[dict] = None) -> FEResponse:
        """
        미국주식 실시간 체결가 (FE)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="FE",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return FEResponse.model_validate(response_json)

    async def FT(self, request: FTRequest, headers: Optional[dict] = None) -> FTResponse:
        """
        미국주식 10호가 (FT)

        URL: /api/us/websocket (POST)
        """
        response_json = await self._request(
            method="POST",
            path="/api/us/websocket",
            api_id="FT",
            headers=headers,
            json_data=request.model_dump(by_alias=True, exclude_none=True),
        )
        return FTResponse.model_validate(response_json)
